name: commitfit_tabata
description: "Tabata workout tracker with GitHub-style contribution graph."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  google_mobile_ads: ^5.1.0
  wakelock_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/tick.mp3
    - assets/sounds/ready.mp3
    - assets/sounds/complete.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
